name: validate modules
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules:
          - ansible
          - ansible-lint
          - awesome-ci
          - black
          - checkmake
          - conftest
          - devbox
          - devenv
          - flakestry
          - flox
          - gofmt
          - golint
          - jsonlint
          - kubeval
          - nix
          - open-policy-agent
          - php-cs-fixer
          - phpcbf
          - phpcs
          - pkgx
          - r2-sync
          - rtx
          - scorecard
          - shellcheck
          - terraform-docs
          - wiremock
          - yamllint
    steps:
      - uses: actions/checkout@v3
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v4
      - name: Run Dagger Pipelines
        run: |
          deno run -A src/dagger/list_jobs.ts
          dagger functions
        working-directory: ${{ matrix.modules }}
  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        modules:
          - ansible
          - ansible-lint
          - awesome-ci
          - checkmake
          - flakestry
          - jsonlint
          - r2-sync
          - scorecard
          - terraform-docs
          - yamllint
    steps:
      - uses: actions/checkout@v4
      - name: Publish package
        run: npx jsr publish --allow-slow-types
        working-directory: ${{ matrix.modules }}
