name: ci
on:
  push:
    branches:
      - main
jobs:
  flox-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: rust
          args: |
            target_add wasm32-unknown-unknown
            build --release --target wasm32-unknown-unknown
          working-directory: flox/plugin
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Show flox version
        run: |
          fluentci run plugin/target/wasm32-unknown-unknown/release/flox.wasm setup
          type flox
          flox --version
        working-directory: flox
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIX_CONFIG: "extra-access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"
