name: ci
on:
  push:
    branches:
      - main
jobs:
  nix-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: rust
          args: |
            target_add wasm32-unknown-unknown
            build --release --target wasm32-unknown-unknown
          working-directory: nix/plugin
      - name: Show nix version
        run: |
          fluentci run plugin/target/wasm32-unknown-unknown/release/nix.wasm setup
          type nix
          nix --version
        working-directory: nix
