name: ci
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/nixpacks.yml
      - "nixpacks/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v4
      - name: Run Dagger Pipelines
        run: |
          deno run -A src/dagger/list_jobs.ts
          dagger functions
          dagger call plan --src . --path example/samples/php-api --output=./plan.json
          jq . < ./plan.json
          dagger call build --src . --path example/samples/php-api --name php-api
        working-directory: nixpacks
  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41
      - name: Publish package
        run: deno publish --allow-slow-types
        working-directory: nixpacks
