name: ci
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/nixpacks.yml
      - "nixpacks/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: rust
          args: |
            target_add wasm32-unknown-unknown
            build --release --target wasm32-unknown-unknown
          working-directory: nixpacks/plugin
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Dagger Pipelines
        run: |
          fluentci run plugin/target/wasm32-unknown-unknown/release/nixpacks.wasm plan example/samples/php-api --format json
          jq . < ./plan
          fluentci run plugin/target/wasm32-unknown-unknown/release/nixpacks.wasm build example/samples/php-api --name php-api
          deno run -A src/dagger/list_jobs.ts
          dagger functions
          dagger call plan --src . --path example/samples/php-api --output=./plan.json
          jq . < ./plan.json
          dagger call build --src . --path example/samples/php-api --name php-api
        working-directory: nixpacks
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41
      - name: Publish package
        run: deno publish --allow-slow-types
        working-directory: nixpacks
