name: ci
on:
  push:
    branches:
      - main
jobs:
  pkgx-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: rust
          args: |
            target_add wasm32-unknown-unknown
            build --release --target wasm32-unknown-unknown
          working-directory: pkgx/plugin
      - name: Show pkgx version
        run: |
          fluentci run plugin/target/wasm32-unknown-unknown/release/pkgx.wasm setup
          fluentci run plugin/target/wasm32-unknown-unknown/release/pkgx.wasm install jq
          type jq
          type pkgx
          pkgx --version
        working-directory: pkgx
